### ISSUE TITLE
Question: Who to ask about focusring JS event?

### ISSUE THREAD

**Issue by jonathantneal** [WICG/focus-ring#39]
The [Selectors 4 specification] doesn’t mention a corresponding JS event for `:focus`, so I understand that it might also not mention a corresponding JS event for `:focus-ring`.

Is that something to ask here? Feel free to close this if it is outside the bounds of this project.

**Comment by alice** [comment]
Curious what you'd use it for that `focus` doesn't cover?

**Comment by jonathantneal** [comment]
At the time, the thought that came to mind was tooltips, but it was only hypothetical. I was also overthinking how the polyfill could (in theory) rely on the `focusringin` event to attach the additional classname.

**Comment by robdodson** [comment]
I think this is an interesting discussion, but not an issue with the library per se. For a tooltip you could do it primarily with CSS, similar to http://heydonworks.com/practical_aria_examples/#input-tooltip but using `:focus-ring` instead of `:focus`. That way it wouldn't display on mouse click, but would display on keyboard focus. Giving you a kind of pseudo hover behavior.

I'm going to close this issue since it's not necessarily a bug. But we can continue to discuss stuff related to a focusring event here if you'd like.
